[workspace]
members = [
    "01-initial-setup",
]
resolver = "2"

[workspace.dependencies]
#alloy-contract = "0.5.2"
#alloy-network = "0.5.2"
#alloy-primitives = "0.8.9"
#alloy-provider = "0.5.2"
#alloy-signer-local = "0.5.2"
#alloy-sol-macro = "0.8.9"
#alloy-sol-types = "0.8.9"
dotenv = "0.15.0"
eyre = "0.6.12"
revm = "14.0.3"
tokio = "1.40.0"
tracing-subscriber = "0.3.18"
url = "2.5.2"
