[workspace]
members = [
    "01-initial-setup",
]
resolver = "2"

[workspace.dependencies]
alloy-provider = "0.5.2"
dotenv = "0.15.0"
eyre = "0.6.12"
revm = "14.0.3"
tokio = "1.40.0"
tracing-subscriber = "0.3.18"
url = "2.5.2"
